config/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('photoapp.urls',namespace='photoapp')),
    path('users/',include('users.urls',namespace='users'))
]
urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

photoapp/urls.py
from django.urls import path
from .views import *

app_name = 'photoapp'
urlpatterns = [
    #!Attention list urls,first lists simple urls,after all list primary key and slug url listed in urlpatterns
    path('',PhotoListView.as_view(),name='listphotos'),
    path('photo/create/',PhotoCreateView.as_view(),name='photocreate'),
    path('tag/<slug:tag>/',PhotoTagListView.as_view(),name='taglist'),
    path('photo/<slug:slug>/',PhotoDetailView.as_view(),name='photodetail'),
    path('photo/update/<int:pk>/',PhotoUpdateView.as_view(),name='photoupdate'),
    path('photo/delete/<int:pk>/',PhotoDeleteView.as_view(),name='photodelete')
]

users/urls.py
from django.urls import path
from .views import *

from django.contrib.auth.views import LogoutView

app_name='users'
urlpatterns = [
    path('signup/',SignUpView.as_view(),name='signup'),
    path('signin/',SignInView.as_view(),name='signin'),
    path('logout/',LogoutView.as_view(),name='logout')
]

photoapp/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.validators import FileExtensionValidator
from django.utils.text import slugify

from taggit.managers import TaggableManager
# Create your models here.

#!Photo
class Photo(models.Model):
    title = models.CharField(max_length=50,unique=True,null=True)
    description = models.TextField(max_length=250)
    created = models.DateTimeField(auto_now_add=True)
    image = models.ImageField(blank=False,upload_to='photos/',validators=[FileExtensionValidator(['png','jpg','jpeg'])])
    submitter = models.ForeignKey(get_user_model(),on_delete=models.CASCADE)
    slug = models.SlugField(blank=True,unique=True,db_index=True)
    tags = TaggableManager()
    
    def __str__(self):
        return str(self.title)
    
    def save(self,*args,**kwargs):
        self.slug = slugify(self.title)
        super(Photo,self).save(*args,**kwargs)
    
    class Meta:
        verbose_name = 'Photo'
        verbose_name_plural = 'Photos'
        
        

users/models.py
from django.db import models

# Create your models here.

users/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class SignUpUserForm(UserCreationForm):
    def __init__(self,*args,**kwargs):
        super(SignUpUserForm,self).__init__(*args,**kwargs)
        for field in ['username', 'password1','password2']:
            self.fields[field].help_text = None

photoapp/views.py
from django.shortcuts import render,get_object_or_404
from django.core.exceptions import PermissionDenied
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.urls import reverse_lazy

from .models import *

# Create your views here.

#!PhotoListView
class PhotoListView(ListView):
    model = Photo
    template_name = 'photoapp/list.html'
    context_object_name = 'photos'

#!PhotoTagListView
class PhotoTagListView(PhotoListView):
    template_name = 'photoapp/taglist.html'
    
    #find tags input url
    def get_tag(self):
        print('slug value ', self.kwargs.get('slug'))#return none
        print('tag value ', self.kwargs.get('tag'))#return tag value from url,we used value except than key
        print('Working get_tag method ', self.kwargs.get('tag'))
        return self.kwargs.get('tag')

    #return photos matched input tags
    def get_queryset(self):
        print('Working get_queryset method')
        return self.model.objects.filter(tags__slug=self.get_tag())
    
    #tags passed to context
    def get_context_data(self,**kwargs):
        print('Isledi get_context_data function')
        context = super(PhotoTagListView,self).get_context_data(**kwargs)
        context['tag'] = self.get_tag()
        return context 

#!PhotoDetailView
class PhotoDetailView(LoginRequiredMixin,DetailView):
    model = Photo
    template_name = 'photoapp/detail.html'
    context_object_name = 'photo'
    # slug_url_kwarg = 'slug'
    
    def get_object(self,queryset=None):
        return get_object_or_404(Photo,slug=self.kwargs.get('slug'))

#!PhotoCreateView
class PhotoCreateView(CreateView):
    model = Photo
    fields = ['title','description','image','tags']
    template_name = 'photoapp/create.html'
    success_url = reverse_lazy('photoapp:listphotos')
    
    def form_valid(self,form):
        form.instance.submitter = self.request.user
        return super().form_valid(form)
    

#*UserIsSubmitter
class UserIsSubmitter(UserPassesTestMixin):
    #UserPassesTestMixin => CBV Mixin that allows you to define a test function which must return True,if the current user can access the view.
    
    #Custom Method
    def get_photo(self):
        return get_object_or_404(Photo,pk=self.kwargs.get('pk'))
    
    def test_func(self):
        if self.request.user.is_authenticated:
            return self.request.user == self.get_photo().submitter
        else:
            raise PermissionDenied('Sorry you are not allowed here')

#!PhotoUpdateView
class PhotoUpdateView(UserIsSubmitter,UpdateView):
    model = Photo
    template_name = 'photoapp/update.html'
    fields = ['title','description','tags']
    context_object_name = 'photo'
    success_url = reverse_lazy('photoapp:listphotos')

#!PhotoDeleteView
class PhotoDeleteView(UserIsSubmitter,DeleteView):
    model = Photo
    template_name = 'photoapp/delete.html'
    context_object_name = 'photo'
    success_url = reverse_lazy('photoapp:listphotos')

users/views.py
from django.shortcuts import render
from django.contrib.auth import authenticate,login,logout
from django.views.generic import CreateView
from django.contrib.auth.views import LoginView,LogoutView
from django.contrib.auth.forms import UserCreationForm
from django.urls import reverse_lazy

from .forms import *

# Create your views here.
#!SignUpView
class SignUpView(CreateView):
    form_class = SignUpUserForm
    template_name = 'users/signup.html'
    success_url = reverse_lazy('photoapp:listphotos')
    
    def form_valid(self,form):
        to_return = super().form_valid(form)
        
        user = authenticate(username=form.cleaned_data.get('username'),password=form.cleaned_data.get('password1'))
        login(self.request,user)
        return to_return

#!CustomLoginView
class SignInView(LoginView):
    template_name = 'users/signin.html'
    

photoapp/templates/photoapp/create.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} Photo Create {% endblock title %}

{% block content %}
    <div class="mx-auto">
        <h1 class="mt-3 text-center">Add Photo</h1>
    </div>
    <div class="form-group">
        <form action="{% url 'photoapp:photocreate' %}" method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success mb-3">Add Photo</button>
        </form>
    </div>
{% endblock content %}

photoapp/templates/photoapp/delete.html
{% extends "base.html" %}

{% block title %} Delete Photo {% endblock title %}

{% block content %}
<div class="form-group mx-auto">
    <h2 class="text-center">
        You are going to <span class="text-danger">delete</span>: "<i>{{ photo }}</i>"
    </h2>
    <p class="text-center">Are you sure, you want to delete the photo ?</p>
    <div class="form-group">
        <form action="{% url 'photoapp:photodelete' photo.id %}" method="POST" class="d-flex flex-column align-items-center justify-content-center">
            {% csrf_token %}
            <div class="row">
                <div class="col">
                    <a href="{% url 'photoapp:photodetail' photo.slug %}" class="btn btn-primary">Cancel</a>
                </div>
                <div class="col">
                    <button type="submit" class="btn btn-danger">Delete</button>
                </div>
            </div>
            <p>This action is irreversible</p>
        </form>
    </div>
</div>
{% endblock content %}

photoapp/templates/photoapp/detail.html
{% extends "base.html" %}

{% block title %} Detail Photo {% endblock title %}

{% block content %}
    <div class="mx-auto">
        <h1 class="text-center">{{photo.title}}</h1>
        <p class="text-center fw-light">Uploaded on: {{photo.created}} <br> By {{photo.submitter.username}}</p>
        {% if request.user == photo.submitter %}
            <p class="text-center">
                <span><a href="{% url 'photoapp:photoupdate' photo.pk %}" class="text-primary px-2">Update</a></span>
                <span><a href="{% url 'photoapp:photodelete' photo.pk %}" class="text-danger px-2">Delete</a></span>
            </p>
        {% endif %}
    </div>
    <div class="row pb-5">
        <div class="col-md-8">
            <img src="{{photo.image.url}}" alt="not loaded image" width="100%">
        </div>
        <div class="col-md-4">
            <h4>More about this photo</h4>
            <ul class="list-group list-group-horizontal-lg list-unstyled py-4">
                {% for tag in photo.tags.all %}
                    <li><a href="{% url 'photoapp:taglist' tag.slug %}" class="btn btn-sm list-group-item list-group-item-primary">{{tag.name}}</a></li>
                {% endfor %}
            </ul>
            <p>{{photo.description}}</p>
        </div>
    </div>
{% endblock content %}

photoapp/templates/photoapp/list.html
{% extends "base.html" %}

{% block title %} List {% endblock title %}

{% block content %}
    {% for photo in photos %}
        <div class="col-lg-3 col-md-4 col-xs-6">
            <a href="{% url 'photoapp:photodetail' photo.slug %}" class="d-block mb-4 h-100">
            <img src="{{photo.image.url}}" class="img-fluid rounded" alt="{{photo.title}}"/>
            </a>
        </div>
    {% endfor %}
{% endblock content %}

photoapp/templates/photoapp/taglist.html
{% extends "photoapp/list.html" %}

{% block title %} Photo Tag List {% endblock title %}

{% block content %}
    <div class="alert alert-primary">
        <h2 class="text-center">Photos with the tag {{tag}}</h2>
    </div>
    {{block.super}}
{% endblock content %}

photoapp/templates/photoapp/update.html
<!-- photoapp/templates/photoapp/update.html -->
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="mx-auto">
    <h1 class="mt-3 text-center">Edit photo {{photo}}</h1>
</div>
<div class="form-group">
    <form action="{% url 'photoapp:photoupdate' photo.pk %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{form|crispy}}
        <button type="submit" class="btn btn-success mb-3">Edit Photo</button>
    </form>
</div>
{% endblock content %}

templates/base.html
<!-- templates/base.html -->
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Django Photo Sharing app | {% block title %}{% endblock title %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-wEmeIV1mKuiNpC+IOBjI7aAzPcEZeedi5yW5f2yOq55WWLwNGmvvx4Um1vskeMj0" crossorigin="anonymous"/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" integrity="sha512-iBBXm8fW90+nuLcSKlbmrPcLa0OT92xO1BIsZ+ywDWZCvqsWgccV3gFoRBv0z+8dLJgyAHIhR35VZc2oM/gI1w==" crossorigin="anonymous"/>
    

</head>

<body>
    {% include 'navbar.html' %}

    <div class="container mt-4">
        {% block content %}

        {% endblock content %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-p34f1UUtsS3wqzfto5wAAmdvj+osOnFyQFpp4Ua3gs/ZVWx6oOypYoCJhGGScy+8" crossorigin="anonymous"></script>
</body>

</html>

templates/navbar.html
<!-- templates/navbar.html -->
<nav class="navbar navbar-expand-md navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'photoapp:listphotos' %}">Photo App</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo02"
            aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse flex-row-reverse" id="navbarTogglerDemo02">
            <ul class="navbar-nav">
                {% if request.user.is_authenticated %}
                    <li class="nav-item"><!-- !remember the row,after finish worked come back this row, for addding active class -->
                        <a class="nav-link active" href="{% url 'photoapp:photocreate' %}">Add a photo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="#">Hi {{user.username}}</a>
                    </li>
                    <li class="nav-item p-1">
                        <a href="{% url 'users:logout' %}" class="btn btn-sm btn-danger">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item" style="padding:5px">
                        <a href="{% url 'users:signin' %}" class="btn btn-sm btn-warning">Sign In</a>
                    </li>
                    <li class="nav-item" style="padding:5px">
                        <a href="{% url 'users:signup' %}" class="btn btn-sm btn-warning">Sign Up</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

users/templates/users/signin.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="mx-auto">
        <div class="form-group">
            <form action="{% url 'users:signin' %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="btn btn-danger w-100 my-3">Sign in</button>
            </form>
        </div>
        {% comment %} Already Registered {% endcomment %}
        <div class="text-center w-100">
            <p class="text-muted font-weight-bold">
                Don't have an account?
                <a href="{% url 'users:signup' %}" class="text-primary ml-2">Create account</a>
            </p>
        </div>
    </div>
{% endblock content %}

users/templates/users/signup.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %} SignUp {% endblock title %}

{% block content %}
<div class="mx-auto">
    <div class="form-group">
        <form action="{% url 'users:signup' %}" method="POST">
            {% csrf_token %}
            {{ form|crispy }}
            <button type="submit" class="btn btn-danger w-100 my-3">Create account</button>
        </form>
    </div>
    {% comment %} if Already Registered {% endcomment %}
    <div class="text-center w-100">
        <p class="text-muted font-weight-bold">
            Already Registered?
            <a href="{% url 'users:signin' %}" class="text-primary ml-2"> SignIn </a>
        </p>
    </div>
</div>
{% endblock content %}